# generate-eventlog-v2.ps1
# Continuously write test events to Windows Event Log until interrupted.
# Use Ctrl + C to stop the script.

Param(
    [string]$LogName  = 'Application',
    [string]$Source   = 'Phant0mTestSource',
    [int]   $EventId  = 9001,
    [string]$Message  = 'Continuous test event generated by Phant0m validation script.',
    [double]$DelaySec = 1
)

# Ensure the event source exists (requires Admin when creating).
if (-not [System.Diagnostics.EventLog]::SourceExists($Source)) {
    try {
        New-EventLog -LogName $LogName -Source $Source -ErrorAction Stop
    }
    catch {
        Write-Error "Failed to create event source '$Source' : $($_.Exception.Message)";
        return
    }
}

Write-Host "[+] Generating events every $DelaySec second(s). Press Ctrl+C to stop." -ForegroundColor Cyan

$counter = 1
try {
    while ($true) {
        try {
            Write-EventLog -LogName $LogName -Source $Source -EntryType Information `
                -EventId $EventId -Category 0 -Message "$Message (Count=$counter)" -ErrorAction Stop
            $counter++
        }
        catch {
            Write-Warning "Write-EventLog failed: $($_.Exception.Message)"
        }
        Start-Sleep -Seconds $DelaySec
    }
}
finally {
    Write-Host "[!] Script stopped. Total events generated: $($counter - 1)" -ForegroundColor Yellow
}
